### ISSUE TITLE
Error in Lua `SetStatusBarColor` method

### ISSUE THREAD

**Issue by 3axap4eHko** [Bodify/BetterBlizzPlates#17] opened 2024-09-08 03:41 UTC
Error occurs with enable friendly healthbars 
```lua
1434x bad argument #1 to '?' (Usage: self:SetStatusBarColor(color [, a]))
[string "=[C]"]: in function `SetStatusBarColor'
[string "@BetterBlizzPlates/modules/castbar.lua"]:730: in function <BetterBlizzPlates/modules/castbar.lua:668>
[string "=[C]"]: ?

Locals:
Skipped (In Encounter)
```
Profile
```
!BBPnYxxSXX119hsgLiN2eZV)usCLSLICcIaPK1h2OooKl5kYerY1KRLQDCI3z39U7mLZoZ1ZmlPOQJFGOP1iia1XVfOhAGGrFX)FjkVLIg3Q(qtB6)KnmXPPfjiPmpz0G6u6cJ2c06Eo3VM7DMlLtacH1E)(Cp3Z93535CNEoZ8nCsCELE)9UxaD(wfd9dJw)QZ)z7d(F0PQ77ehVCqdV6ojHrLI8ibn83zJ6o(K(Ot3iC1WKL8AqKfSeXXpXTMt0YbL3I4s73fkC1YfNlIe4SwG)oU0rPKevhY6irVDCYnj17KqufwMevNeKSXoTRf6dnmWPnH67KqMRtKZ8DA2K3Wx1b(NSPT7(SHJwVOtCcmjCPNOPyITkfBqjp)es01iXXR4f4LatWJfM4sIwL2GKw(nCsQ7EnV4KQ0pvDONMhxoWVh1Hcl2wU(W)h(NSHCHWGevHvPJjQ)6K6yPQsCPJuVtCsy7kKBM0jsjVOdUqKtRWGMS(SWzNF(YpcDqtH(VF5W4EUh1jkzNYHEyp6shgxOIv5nCHvIpmD)i3JnOG4EvqsbcSxOdjovwxb(hRe2akyOeNOwA7cpdoc0rYk)f7lhZf2ujrQFEDsJIrHXXlgqAd7NJPnvMpmQbjAdxpIFdy8BqA60XpPKtdYADsG5vmkv)NlDkVgh9l(NExyVnAhMumE05tabZLgmQNbB13G16zE2ED)Zf1ENcHnla7rfwG40iQEy72qZ6L1fhCXUtnA3JL2QUhF)5jWmPWzxQdkNEKUtZQ549o8pnxvF1fCI20nStqdzT652FVC1Io6cErKcZ7e7bI4nZ2ZhT5hnxtQTWNRaOJR614Q571Xxe2oDlSOpbxoo(fo7gUoTDc0MXF)8lUL999A4e5vydNKDIuv9Lot(bySvCA1j(SzfGQ59o)M8Tz4v8IIcJkSCBNwK4cNf6cIQbrLZ3GP2G6f5Lu4gH(BHnyXaxNcMlKJ(t(BZlGQerCcucOEF7NYIy)6HEnkuboKe5HshkCGjort88JY1M7kAcUgG6rhvE2ViECIPNHNlQcgAqn3vjDsIC85wSGJSsdFpEF91dD4mNqehfMSURtqlYQsdrC9DUTh6WMh3MlOUBy08xBXsvOtkSYKAJPChO)DQ5dtNHmmbTya(RG9cx2eB1oTRrIIL2lGZUWrGAojgwhowF7zyDz3599U1TCIAqNeTnQmqWpR90uWEpPr1d0o4INl)i0tAyHLFaVib13jn4lhC8nmoXfm3l2nCBWUBfVeyUVNdATFzrtoFL1kthNzywV3Reg6N4rblWctMRgg4jnx6bIa2K9Xl33mN7rt)d0r6ILNoMSIhCOimig6OMHGuOI5gxQrVXA4fJI2Ix3jQuiCZYAbxlSLxaucZ2QQjy1R4grG2CcLaH3Tc7BE3sEN1io1IdJQLztV7SqbmzGEFUwZM6xIT2wKiFh6sSEcxCxHoLQWna5jt8F1oW2ONtq8GZcAFCj1ITPUG9O4nG59MlrWBoUkDyvBzTJ)ZL)qx6rp3SN)I0JLrFUitpwOU4sh0CJNFFWWzgoPAUWQoUBwgBsj4kq6G4FJFUsRV8Z(uvE(N)CvQuIoUzVUAi2eEFpO5zf(pouTwP6vGayTOAXWXdcF9OFmf2SnevYJh4T6GUWGZCxHki7Ut6ukuaYgfJyrwoy(wGEZy53QeB)diqVeRob9nE4RVEtFNwXJwRDNi)W6UGLgMv(VEuEJytcQdWYeSYuOCuycPEcm7kub(VAF9Up7OD)8IwF03(jY14dk6qDQ7btilny8EM5BMF46VOFyNg16eb3aARn3(FnFBgQyi7cnyw6TjXsZA8A5NASlVQ5f0W6W8vwl)WmiRjKGc3WX33Me4x)1oKHPvKtnBdtV)f)x5hMrkr8lSwnc)Q6B4G7qB(iMJuXgwKcq7AHN0kC2fiTdluMKy2QHN0EJCzcVdBOg705xuxncHC4f0YQS7n(Yw0IK2ak8uDiGi8SuqxQa1X3XC4s(zwUshp3Gd2gjWDUTTj5FRelBxYMvboayv6)LxmFRofhBek9kCwy3ENc4MTRZwKcXWbVclVG5e(BzzGxoOjjkabezvKoEpV4ZyPvxZ7f6a39dawA7yBnE2Fv(nIvCcCoS13rF3puUgChW4sJAGzesuMP0DEoltP1QftI26q1ngV3387kAvnwRIyTQmIEDdIFtam1wHBcanZOr9qwGkbEfed2vk6dOQIpmnRV6OwMKLJ3PjAzmfGLzR67fE58tYXaeEnc3UWzlZAsH1jFQseNOSBu3opcT92yZDA2jAhBs8FWhl)8Bab(YR5fSPvTWVZTTSO2iXjXREHsOtiwv4)m5xtdTrsyaaZVJ)2WDQwhR3nVg)bSwfVPNnJ6j2oxTrN617uRt8HQv8ULS0QkrobGcUFH58SDBWrhBICn6Eag722V7O3h8zTC3rLDGbj5qp29d)DZFGaQk4yuqqUdeV4rYlQUbEDX6DIDTUa(L5AW(ydsvwO9lqJGyweGVg1IV7Z577UR0nyaSIjAvb8SpnCZUomsgkHdyWa2GsQlR1(MGuGElRhYSgUpd(i2qX8Aaf2eWKbhE3hCMZDPzPtP5gGevfPbhuPRAfUC9WarpDcROCsXeod9mjO0rnHwsaZEUGgGx4ntW(AHWTbqUJybK72HU0XBqJxlcT3VA4CTAffQiaQN(6bMbc0ExdXpAa5RecdQ3mG8wGutXlJgCwSO1jW)L3weU0nc8kG5A04z8NHHEfrNvvmLfCEOyqcqeMHqcb6XakxsI8)Owd9aRHH07hucHkj0rYajwt3aQcBAGRxuFdPYamlGYmfcs2qGW2ppDe5iZDysrGgo2JGD26oEnAdDGMQKMoIZnNZh0fo)SNBg6iChmv0OXHX7sN0quUyGpo3BijoZY5aDoUm9zA1WK1ck1X3FjW5RmunXLKF87dPxQFJRHS0t(Rp2X(mFGpWhOV9qpnN33P(MmQOOdOl0Vbyo0Dz6yQvb4Sh3Jk2shfJxKoqKqmbEhVvzozHJNzRwt7yqbxFRWWHlnji3k4Nvkfse(lmyohqJRUV6eVO1N0MhKzCv6yMsSLeBVRWM3vP9RVS5EFiKXWjrnwqhkJZvc1mLasEwNj5ED6WkUmK0yGmvGY)7m4Gfa5pDIS2MqFya3Y9Bmc9eMgjyR2NMUCBAyucy0VkCi2qS5VJPrGrvoMdwRsTHufpdfSjQlzXYb)uhEMzdsscal5Zr258GpW0HZSNke(fYir4EOjgxgNi7P2V4c2JNZToqTkobub5uOmwE3PHJeDqxPheKmrjZj7poVqCYU5hSHdkHamuvpxLorotaRtId7evN4ENMkgoH6z50iUwwbxasMQ58Tmjvom0C1LoumbKGASDVE42U0ZEFoBUyqJkETjCBgVEovmuduWRKM0NB2BxWC86lF1LQqNkhlWGSBbsDV2o(GIIL(KT)De6eoa2PDI1JgGGCjqMy9Em0ZA4kmtZtAdN79K(FJIR)BaYWz2L6aaWB7v39v9KQVaiIx9gEawpqHoMbW5JUqoeE9ITU7p2T7Bcv)EsArrkrpfJm6dPbqTH2m96mALpLDoNnQjNesWlxWAau)fYdc0yM8QmMfA7eqyWTD(RV)ZJU)eOAFW8(IA2NvIc99RP6Z)M7FFExWnw)cCx3oLvpDn697oxTW2EboivgmH9sx4(lS3DLqWhEp5S5V6(pB2FbWp1gG7QmjiB7SNx6DU)tjWE4TAf51Mpa3Z6aOb20c13D)4zGipBE))OdkvYom39)N2mFh)VqhLtnRmcjxvXrlO6gchLSHmBTaI7(Mx0uLoA6bmoqdzqU6hH6VfyoYXVnACkUAw(142lTfRl1n2vpqd(jV(JAp4FU7JM7GJLQBPhlgojwmSn1PoCdb7Y1sErXyuVmV5bUUgpk)YNe8iFRDBavevJgaKtT3fpRZmrTEDoZVaM5zUc(3RCE8Vx(kWM98Eqng)QxPW8XE3Iml6L5wDF7Pb3fyEjGNPVb0PUD)nUD)3F8(W2D(lJ)9IpgQQCW4JC6VD33zw0hiE7QX97rR(x6X6P7BwfQ60)r)SUVZtG0MXRA3N3AVIv9d)9)3GQE03kbQ5iqn941ShwvVGOsh9Y)DS(7fpcuRtd16L41Y6cLv)USP6352q9)Oq93sVxL16b)AVcwlWbnXS8ljML90hFyFGl(vzd7xpcQqrOcpx2UbRvVd9k4k4TFcOshbQ0xWMeP3HwbQuYptm)DTnF69b)hH5d4oVys3X2O133yqUO4ze1Yp7WHD1h7hEvORA8AqDEcOovtfxxMjUU4SsXlBGh6pNjiUt)CbXUixGxdq1yBL0))ZZGtGEFZVluzq)7vveVKoix4sSbH)3ZZhKsV8FmBqM5BkK2FXS708j(cOm4D)qIkfyB117WJIvAShcQ0qqLEH0r(rFmer8JXvmKRo2a33l8YBHRGJxJtcJEBGn83(byv9)S77C1J(wFgHCtRspgtUD5lI)D2llvl)hy7fF1rH6pbi3KKcLPV5vE2)sSVh70qD)WqF3mJYwVd1I1zFL1e6ioz30Eu2Y6cxuw)7W2hE3sq9FeO(3YMo1rV8pGjQMaQ0uqL(dpurfVp))XMd355495UsQ4SPiC0lJQ0FlUOAxj7J23VMIDC8)9b5hY3TmYmLf9lSY9D7)eCg)E9Y1VVNE0m10WUaxw0Nyzo73HncV7Ic9MBE4cpS(x9kNehKF9xtSrxtR6ST4lmlkCMvQb9Amv334lZN)0Pv8klcqCPWOwHjjebrZz3Ah8TbjLKrfWmmdil3TbayOEmvnCsbdN64zd)KScWneMKeeUnGVylmQOMXZI5huYrPN4qDZHbdDeTadnhdST4sPnEbyXcDB)girNZ3hCg4yzcI3AbL9D2bqFWVDRF86oOMZ3jH7AOBg6JePpruwV8z3IExTGAvLonxqy4ikBIZd7BJ0WHUabNdnu48zImMh3V1etW84opDu8jYu5c2Ckzav5zoI0ZL1c4xQJxHVPhDUg)bawfWvTsE3K0GfrpxnVSOwtrMHWy)kWISCtPeAuesGKNIuebvvELGAqW0fMje8xZSfiaGKhzujVTaOr4qE1oaCmgCNdHMaEF0VlL7qKe(YdCqgLXQ0hsPuSGgBxP50KrOuv8mXxQs(fK)AAYg4QhGDM)97jNlS53dyliXCo5SO7Z0sGdaJKXdmjdrdNBxhz5shuNiQUUAoOjj4s3dTuDd(cCWza8EBkyve9vS28RvPYAROXjLqQLoz)5hOSsmFl(POtIJROI58UMZhZEbImiqgPzDUusdK)XS51SmJhQsN0M(Q0P6tyRT6CLnKjWzzy(ZjDqH5dOXxdaDGWSZiP79XUiGFMl8NhGy3If2V0dXV9B8g)s2H4J10i15Kr4MBbYvLqzRgMXsqF9S0t(k93pY9tF73sEwqmFNWENY5mQNSSIVe7WJKJSYfvr7ETaxn7WSS2WXNv1(P5sFSH5uxkfqBaxeK44kmp4fv3h0OyeUS8cU0jouAL7wwzIGRAlo(13JDUliJQpFaNuXCDEgOyCVowwQ6emL4QXmTbpBmP3RVNXWZg4uEf1o0RssYm(jHekX5Aj9CCUehjBYvWYLdy720FjTKwsK)GOic7g19ftMLC71vSOw1UT7ux(OtDFytcknFSfu6tWuvAvGTIUHxIBzC7bKUh)WUTNjkCHXbtaP4AZEUlDUzRLLrv5oIKp(d488YUPCBpkl9fH78D4BcZX8jgvuNYQ5i(M4NNowNysrDhXve6Mp3S0UCB88uiYC0e5qCIdn5GGdGSeIswUCi9AJIvB(73SzwIdlli66Q(iTFPtFzcKc6zG3kWY2sjsry6TT8uYuLDsJsyQpRsn5HplASuBUgH0IvxqamwM95LKEWtFOyglESTHIHa4SWTdeGLwlGVxc3AFkR0TBQSSxejKscwJMWsYRDHdlB4SfbSZpDQUTDcnuaHmlwCpXb8MRg30eBIF5V4C2e0jKaY0suxU4SkBBPKXLJZdaOdB7Uprfki2X39mYdVBvsYEfp1qlnOtFA8vT38ojWTGijyb1jDNU33NQxe2nJWml6gWcdQ(L6(SxIZN2UebcmxBnKo1I30PnfgjCdPWJFHcNTbCnwcPqBYJWgtya)XUwIlpygikr62asl277K8vVMxtsn)WW2VVv9EI8lyH7ZQxmzw6j)E3(2VX79EVx3JFNn6ud2FB2Pf2g6XZDJ9tJzUHKZSd0qLlcFiZyhEQNNFKvUXnMfaty32ehA5WzaTkJbvEuDLGzq2Rs5EKaxLQckq5TwuKI86b2inf5l)bN9CZCE6XZHaueSqbSPjmCoHhgLISGS6ABvE(QzYnD0UcMCmRVrOVxJ9nV3zcnmpstbI19yMx2WYWvU1Rbnz4xeLCdtt8nHXYFJdhAOvZCYjQlTGva82seYrTL48mCoyOSYgcCegb7nfuH0MUe9AHXGzRbsLiR1jX3lGC3klT8QR90vU2YRUy(aekUrvU7yZONucAzrcsim3wTuYI3eGyXlU)uZnvy3ncIKuKUhwCHZ84iYLrc83CWYliYXxQHptIKOwk3ZeXAqvDMZDL7KkPOtc()5uydNG4cfdHJIbW4uyfsdVoT1oyGBPYRSNaVYn1DQLdudgC3ZOM(KitUGUFAWRbdi(CGs8KDg5SMKiCRFytDnv4)NWaqfdA864WwhZtwZ2iC8xb22eG0uhcte896(1t2vbQDBzwRinl6pneJXQyMFH9nFUjUkVdXGwha2YfECS0t(lMEAgPbl9K7T3E)cWIzFwa(OhmaZSYaqNKHj)W5c8AZOV39WSsYfpdKl01vZfesUtIvLhT0me9t75Lpq(mseMGgcwLMZoHFPfxC1klUEM3jKi)ODOpqKqfOk9ebHrTD8fMbWJsTPHBJz5o(tXiBwzywjn)7NmZyRrvu101kUmfh4pro7Llasy8Un22(o0Hy3xygOC6XN9Xliu7yg3kSnaWUaZ)PclVqUSMrlZcgwtXslDjM2U9an4sJzCkm1HOFoDISGNvrXQ69KNd5B2tyFuyjCZOMAqPGlh36bOvP1RMn(r41jS0OFk7oER79TzoTlTWQssinMk5oYbom2VbbemYlXo7kxSNCpzkre1YHYa(zp8qrjVBMkB4vEGCp8T(sx68JHZ73HithSjYSfNUa7JEAtXsgK2SuKdoOWygNdhil3yI(5tCF8)dqFgLKMpbtdUSAzcbIuBuQW2Wzj0gOT8uD8QVjU3c3YYUmLjkvdv1Sp)aU46tEFMBgV6USzIugdVQKLsWa8WuRppKu2SwRED)oninyNvxbKRNhF4jfUVo1Y0v6Hrr)JcBQwUINVOshfUDdgofUK88ZEURKsCJTZpwydfXvkE1F8qR(ru4QyjCKYHVS9R8zgzdSksXQIloXUC2NDe)4UPPwK8(24Zj43Hoc3btH5cjYc3dYOlcB95VT19UAEv5AMrvcgUv3qEDsuc0v(zajpRMdRY3zd)j2KnbwuPt6rsZ)m10d0kIjj4dgAU64lEe2gGlwJWRXJGBjsFYnReIN53GsinkFKzaq6xKoMbMxUYa3a9KgLK5rUwWUcGXtw1chrkRMvZUJMQHF63F3T5XRrpVtfMwm5c)ZZtbt1AGRM9t75BtpLvG4gKS9ApaD0SxVQ0tpKBP0yKjFsFv0hmVK4gf2PLlSPin6AGc5GmBvacsRNs56xfe0JyGFJD)NxmdYd(qFZ)m84pfVmo2WZTyFjpNS(dryKX3rTBQhZgPDmladiE(HGRiIhQTqBkR5DH88))EgBtUhG0YCny2HZeWGbg1ayiLunHltqjJKnFTKzoh7PvnBMxMO214hwST6l3lxJRgDDh46Uzbta5YcxuvAaJ878zez839tfUk6)yRw8nUyaNWcDIa4uLV(IUGtZYasWVhWmDhRkCm28UTJSNc3dI9eoAbBDjWoHG81sGJwDWOpkEbHgwXK2nZS9icSvotn8QVVYPkrZhrdJEk4GQgG8yPuh6Layn1q1J3hhKrtRAgs(yhkr8X4rhLpgPV4TtYFfZQ33wkrnDFUUIh5R69RPv4xOR8bqRERAAL(fvLQEvAAL(8Isvp(mTYQQAP6HMPvQJCkPEqzAfwtwO6nGPvO8zGRsaoTYiYgQErxAf2unHuVElTsBjkv96S0kZv2TQ3GLwHEYUn9TwPv6FGO0Vv(I2unFuVvkTs9LJP6nrPvyBzHQ3)KwHbQ(v9GN0knujIEO8f(cQMQEgsALQEj72EUrDJLDS6fcPvyhLqs9uG0kDlL8n)t(P72QM(UwKV3uUTzzNzNuD3Fu(s)ps73s5l9wkX0e5l8pu1u1t0rR0xunSQhJJwPFP0D9JKV0xckLoGkmHgrdCSm8uaa4ewFgCBNy8vs7GVxXnQhriyCwYE5TXdkysBwOLxhD3WTKFDiq6)ngxn)OrdAY8iOG9ivKINQkDslpqy4EdgyR7XbdjOWAFtbGoJS6bVjBCnsVI74hgUiEuVPpSPJmQ8GoZBOVqo3gxa)qQSUJxmreBKXYCVHwOyI4K9Otj5KHcXMrcZZiZWL(j(TYzro4zUhJ2W1QCTEMlqhj9IcDou33CGQMbdSaPRtlyr8WgjflS3US(t)xqUW(lqsC88JpzHn8rzI8bsHT6(WR1XTNFaP8Ci8njllUvZ)48VUsQCXmp0jJmekZ3ebXhgL8jeKGqmT7ULWDEKmPueO)cxNpwUEqXsPzAofNvdBAePxLm(jW3WzbrTQ5dqsT5EPz18arbxLhdHf6aypzFPfgldKIuLZPTI)pnXqaW)gE8PwpdBQQWLUvn(KaO99RHt3DMpRhtMLeCEqpeSIL1TaXBZXuLL)Jp8VnSImTD9mnpvM4qj(7uxAg6aMriKtGqp0rSItv8Hus6onx)kvHufsBPaAu75)HRzWBmPm7sZAU1itChZDMn22HsX8oyGCXOseEQb0FKJCY3TK)mC3I02D5IEZ3csXorygfG3Tio9lDGaLW)9NP7XJkUtD)WaI4gpzmkHsMhFtY5)5DxYzN2GQGLIo)sKBM)xp4A4gFa(SQbpNIdZxJ9xb(9cLd93PDyenB4spdMCXhEz3zDcfnkIH6mxH7TooSHnlukkmo7ljbBmpsP4RK1wH(ecL9uuSmN3iK3ZfD9(uFwVmvix(0P94lh1YTTsL3CKUCDUPZH0uEtzs)uV)pLPxNoMrIuWV2NNXApKmVdfCDDdxsq2VHmvTNzGC7W5i5pnxsKF4paF9eef7EiVHjmEsdodyEXcShKY7SijyxSDqrxs9nr71QV4xzOw1HAjieANVtp6Zm8dZZ1d3M9nWXk9rY0FBcJ0qGzts(1aIoLr22LDLmPbHEcYqULGmeJ36jhQv6B1JZ)st7FdWYO4bivpHeGSLxAv3ckaYw(GE19KP4YZ)H8Q7PKDSLpzxDFivtT816Q7dNoS5)QC190QsT8H4Q7zKdR1NDKSqlFDT6EwzHw(eA1n9lHLLVEwD)ePt48Ffg6(jHs31jimGRmPN5OQG2xn9jNAykhZJ(yytFEWw)m0tMneTLYIDyWzVR2H)mjoO8RZJ1VBtStkD)vhwE(OUOfJuITVkxiOwE(VIxzUfCoboAxnd7vieba6xd84TmYqshnuXgI9iYhn3vykSHxg)MgAsBPKE9djrmzCVnKmCVS8HQydziBUOgXYWwrnb72D)ZYKajCSt3HNnUS3s)W1TKHBDVmGYXmIlyWP044vWDVkX7eC4pHocrt8lp6m5YyBrab0TeKQyunZN2k5qPYLU(ZARt3gNIdsMX2zZMLi6uNQAJjH19PfIjvWn)56jaHTCeZ16xXl0rHuOxlfg5DRq8t4NmiopkDu7HNqezIJPkLjF8AI9TN4z0chRoV((Vz8HMLouByRab8VwA2qmHfoXfq2z3BJy1WCVhZBomleWm8cwc2YOeuswDx8ZbALDOK72eaEvokSPNp5)7!BBP
```

**Comment by Bodify** [comment] 2024-09-08 05:21
Hey! Thank you for the report. I've seen this mentioned before but have not had the time to take a proper look at it yet. The error itself seems a bit odd and I cant reproduce it, even with your profile. Does it happen in some specific scenarios?

Either way the cause of the problem is the "Castbar Edge Highlight" setting in castbar section. You can disable this.
I assume you've used the Nahj preset and he has this set up wrong. If you wish to recolor your castbar just select the recolor castbar setting. This Castbar Edge Highlight setting is just being used as a glorified casbar recolor that uses more cpu power.

**Comment by 3axap4eHko** [comment] 2024-09-08 15:54
I've noticed this error in dungeons when healthbars are not colored

**Comment by Bodify** [comment] 2024-09-08 16:46
Thank you, that makes sense. I realize I forgot to add a check to see if it is restricted or not. So, once you enter a dungeon, it would indeed error on friendly nameplates.

I've fixed this in the version I'm currently working on and hope to release it in a few days so I'll close this now.

In the meantime, I still recommend turning it off and, instead, enable re-coloring the castbar as I previously mentioned.

Cheers,
Body

**Closed by Bodify** 2024-09-08 16:46 UTC
